apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: redis-chart
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: 20.11.3 # {"$imagepolicy": "apps:backend-redis:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chartRef:
    kind: OCIRepository
    name: redis-chart
  interval: 50m
  driftDetection:
    mode: disabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/redis?modal=values
  values:
    master:
      kind: StatefulSet
      persistence:
        enabled: false
    replica:
      kind: StatefulSet
      replicaCount: 1
      persistence:
        enabled: false
