apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: demo-app-1-chart
spec:
  interval: 1h
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: 6.8.0 # {"$imagepolicy": "apps:frontend-podinfo:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-app-1
spec:
  releaseName: demo-app-1
  chartRef:
    kind: OCIRepository
    name: demo-app-1-chart
  interval: 50m
  driftDetection:
    mode: enabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    serviceMonitor:
      enabled: true
      interval: 60s
      additionalLabels:
        app.kubernetes.io/component: monitoring
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: demo-app-1.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
