apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
  - path: demo-app-1-values.yaml
    target:
      kind: HelmRelease
      name: demo-app-1
